name: Deploy para VPS

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Adiciona chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Executa comando remoto
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 root@186.202.57.183 << EOF
            echo "Hello World"
          EOF
          
