name: Deploy para VPS

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Diga Hello World na VPS
        run: |
          ssh root@186.202.57.183
            echo "Hello World"
          
